sonar.organization=shanthakumarthanus
sonar.projectKey=ShanthakumarThanus_CrisisView-Pipeline
sonar.projectName=CrisisView-Pipeline
sonar.host.url=https://sonarcloud.io
sonar.sources=frontend/app
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info