sonar.organization=[mon-nom-d-utilisateur]
sonar.projectKey=[mon-nom-d-utilisateur]_CrisisView-Pipeline
sonar.projectName=CrisisView-Pipeline
sonar.host.url=https://sonarcloud.io
sonar.sources=app
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info