sonar.organization=shanthakumarthanus
sonar.projectKey=CrisisView-Backend
sonar.projectName=CrisisView Backend
sonar.host.url=https://sonarcloud.io
sonar.sources=routes
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__tests__/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info